-- ============================================
-- P4 차계부 — Supabase 테이블 생성 SQL
-- Supabase 대시보드 → SQL Editor 에 전체 붙여넣기 → Run
-- ============================================

-- 주행 기록
create table if not exists trip (
  id bigint generated by default as identity primary key,
  device_id text not null,
  client_id bigint not null,
  start_ts bigint not null,
  end_ts bigint not null,
  distance_m double precision not null,
  energy_kwh double precision,
  soc_start double precision,
  soc_end double precision,
  avg_kmh double precision,
  max_kmh double precision,
  start_lat double precision,
  start_lon double precision,
  end_lat double precision,
  end_lon double precision,
  polyline text,
  unique (device_id, client_id)
);

-- 충전 기록
create table if not exists charge (
  id bigint generated by default as identity primary key,
  device_id text not null,
  client_id bigint not null,
  start_ts bigint not null,
  end_ts bigint not null,
  kwh double precision not null,
  cost double precision not null,
  soc_start double precision,
  soc_end double precision,
  max_kw double precision,
  type text,
  profile text,
  station text,
  unique (device_id, client_id)
);

-- v2 (2026-08-09): 기존 서버에 적용할 때는 아래 한 줄만 실행하면 됨
-- alter table charge add column if not exists station text;

-- 주차 위치 (차량당 1행)
create table if not exists parking (
  device_id text primary key,
  ts bigint not null,
  lat double precision not null,
  lon double precision not null,
  soc double precision
);

-- 소모품 현황 스냅샷
create table if not exists consumable (
  device_id text not null,
  name text not null,
  cycle_km bigint,
  cycle_months bigint,
  used_km double precision,
  remain_km double precision,
  remain_months double precision,
  updated_ts bigint,
  primary key (device_id, name)
);

-- 조회 인덱스
create index if not exists trip_dev_ts on trip (device_id, start_ts desc);
create index if not exists charge_dev_ts on charge (device_id, start_ts desc);

-- RLS: 개인용이므로 anon 키로 읽기/쓰기 허용
-- ※ URL + anon 키를 아는 사람은 데이터를 볼 수 있으니 절대 공개하지 마세요.
alter table trip enable row level security;
alter table charge enable row level security;
alter table parking enable row level security;
alter table consumable enable row level security;

create policy "p4log all" on trip for all using (true) with check (true);
create policy "p4log all" on charge for all using (true) with check (true);
create policy "p4log all" on parking for all using (true) with check (true);
create policy "p4log all" on consumable for all using (true) with check (true);
