-- ============================================
-- P.Log — Supabase 테이블 생성 SQL
-- Supabase 대시보드 → SQL Editor 에 전체 붙여넣기 → Run
-- ============================================

-- 주행 기록
create table if not exists trip (
  id bigint generated by default as identity primary key,
  device_id text not null,
  client_id bigint not null,
  start_ts bigint not null,
  end_ts bigint not null,
  distance_m double precision not null,
  energy_kwh double precision,
  soc_start double precision,
  soc_end double precision,
  avg_kmh double precision,
  max_kmh double precision,
  start_lat double precision,
  start_lon double precision,
  end_lat double precision,
  end_lon double precision,
  polyline text,
  regen_kwh double precision,
  start_place text,
  end_place text,
  unique (device_id, client_id)
);

-- 충전 기록
create table if not exists charge (
  id bigint generated by default as identity primary key,
  device_id text not null,
  client_id bigint not null,
  start_ts bigint not null,
  end_ts bigint not null,
  kwh double precision not null,
  cost double precision not null,
  soc_start double precision,
  soc_end double precision,
  max_kw double precision,
  type text,
  profile text,
  station text,
  edited_ts bigint,
  st_lat double precision,
  st_lon double precision,
  kind text,
  place text,
  unique (device_id, client_id)
);

-- v9 (2026-09-25): 충전 위치 동네 이름 (주행 start_place 처럼) — 차량이 VWorld 주소 API로 채워 올린다.
-- 기존 서버에는 아래 한 줄만 실행하면 됨
-- alter table charge add column if not exists place text;

-- v8 (2026-09-24): 내 충전기 — 집('home')/회사('work') 표시. 차량이 올리고 폰에서도 지정할 수 있다.
-- 기존 서버에는 아래 한 줄만 실행하면 됨
-- alter table charge add column if not exists kind text;

-- v7 (2026-09-22): 충전 위치 — 폰에서 "차량이 충전한 자리" 기준 지도로 충전소를 고르기 위해 차량 앱이 올린다.
-- 기존 서버에는 아래 한 줄만 실행하면 됨 (실행하면 차량이 위치 있는 옛 충전도 한 번 다시 올린다)
-- alter table charge add column if not exists st_lat double precision, add column if not exists st_lon double precision;

-- v5 (2026-09-21): 폰/웹에서 요금·충전소를 고치면 edited_ts(ms)를 남기고, 차량이 동기화 때 받아간다 (양방향).
-- 기존 서버에는 아래 한 줄만 실행하면 됨
-- alter table charge add column if not exists edited_ts bigint;

-- v2 (2026-08-09): 기존 서버에 적용할 때는 아래 한 줄만 실행하면 됨
-- alter table charge add column if not exists station text;

-- v4 (2026-09-13): 회생 회수 kWh + 출발·도착 동네 이름. 기존 서버에는 아래 3줄만 실행하면 됨
-- alter table trip add column if not exists regen_kwh double precision;
-- alter table trip add column if not exists start_place text;
-- alter table trip add column if not exists end_place text;

-- 주차 위치 (차량당 1행)
create table if not exists parking (
  device_id text primary key,
  ts bigint not null,
  lat double precision not null,
  lon double precision not null,
  soc double precision,
  photo_ts bigint
);

-- v3 (2026-08-10): 주차 사진. 기존 서버에는 아래 블록만 실행하면 됨
-- alter table parking add column if not exists photo_ts bigint;
-- insert into storage.buckets (id, name, public) values ('parking', 'parking', true)
--   on conflict (id) do nothing;
-- create policy "parking photo write" on storage.objects
--   for insert to anon with check (bucket_id = 'parking');
-- create policy "parking photo update" on storage.objects
--   for update to anon using (bucket_id = 'parking');
-- create policy "parking photo read" on storage.objects
--   for select to anon using (bucket_id = 'parking');

-- 소모품 현황 스냅샷
create table if not exists consumable (
  device_id text not null,
  name text not null,
  cycle_km bigint,
  cycle_months bigint,
  used_km double precision,
  remain_km double precision,
  remain_months double precision,
  updated_ts bigint,
  primary key (device_id, name)
);

-- 조회 인덱스
create index if not exists trip_dev_ts on trip (device_id, start_ts desc);
create index if not exists charge_dev_ts on charge (device_id, start_ts desc);

-- RLS: 개인용이므로 anon 키로 읽기/쓰기 허용
-- ※ URL + anon 키를 아는 사람은 데이터를 볼 수 있으니 절대 공개하지 마세요.
alter table trip enable row level security;
alter table charge enable row level security;
alter table parking enable row level security;
alter table consumable enable row level security;

create policy "p4log all" on trip for all using (true) with check (true);
create policy "p4log all" on charge for all using (true) with check (true);
create policy "p4log all" on parking for all using (true) with check (true);
create policy "p4log all" on consumable for all using (true) with check (true);

-- v6 (2026-09-21): 서버 사용량 (앱 설정 탭·폰 차량 탭 "서버 사용량"용). DB 크기와 행 수를 anon 키로 읽게 하는 함수.
-- 기존 서버에는 아래 블록만 실행하면 됨
create or replace function plog_usage() returns json language sql security definer as $$
  select json_build_object(
    'db_bytes', pg_database_size(current_database()),
    'trips', (select count(*) from trip),
    'charges', (select count(*) from charge));
$$;
grant execute on function plog_usage() to anon;
